package br.com.backend.entidades;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTypeConvertedEnum;

@DynamoDBTable(tableName = "exame")
public class Exame {
	
	private String id;
	private String nome;
	private boolean status;
	private String categoria;
	private String data;
	
	public Exame() {
		
	}
	
	public Exame(String nome, boolean status, String categoria, String data) {
		super();
		this.nome = nome;
		this.status = status;
		this.categoria = categoria;
		this.data = data;
	}
	
	@DynamoDBHashKey
	@DynamoDBAutoGeneratedKey
	public String getId() {
		return id;
	}
	public void setId(String id) {
		this.id = id;
	}
	
	@DynamoDBAttribute
	public String getNome() {
		return nome;
	}
	public void setNome(String nome) {
		this.nome = nome;
	}
	
	@DynamoDBAttribute
	public boolean isStatus() {
		return status;
	}
	public void setStatus(boolean status) {
		this.status = status;
	}
	
	@DynamoDBAttribute
	public String getData() {
		return data;
	}
	public void setData(String data) {
		this.data = data;
	}
	
	@DynamoDBAttribute
	public String getCategoria() {
		return categoria;
	}
	public void setCategoria(String categoria) {
		this.categoria = categoria;
	}
	

}
